version: "3.8"

volumes:
  mariadb:
   name: mariadb
   driver: local
   driver_opts:
      device: ~/goinfre/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: ~/goinfre/data/wordpress
      o: bind
      type: none
networks:
  inception:
    name: inception

services:
  mariadb:
  image: mariadb:ahsalam
  container_name: mariadb
  build: ./requirements/mariadb
  volumes:
    - mariadb:/var/lib/mysql
  env_file:
    - .env
  networks:
    - inception
  restart: always